spring.application.name=server

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/feedapp
spring.datasource.username=admin
spring.datasource.password=qwer1234

jwt.secret=12345678901234567890123456789012
jwt.expiration-ms=3600000

aws.s3.bucket=feedapp-photos
aws.s3.region=ap-northeast-2
aws.s3.cors-origins=http://localhost:5173
